# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d57bc2a39560d667c0c3209c633afebd80ebd27c705e4d66a92069bd98ca168a25c8a113c6a638db3d438ef07112fb25291cd274e657aeb608fa722a925479c2

test:
  secret_key_base: 1aaa54fc24777586405d39c8fae5a630c6c375f32c62affd64f6f54b33818d0aadb1841325eac6f3ebf589b533b28da8a4965b054dc6640d3eff32d35688bdb9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
